---
definitions:
  config:
    /hst:hst/hst:configurations/common/hst:pages/service:
      /main:
        /othercontent:
          hst:referencecomponent: servicepage/servicepage-other
          jcr:primaryType: hst:containercomponentreference
        /toptasks-bottom:
          hst:referencecomponent: servicepage/servicepage-bottom
          jcr:primaryType: hst:containercomponentreference
        /toptasks-top:
          hst:referencecomponent: servicepage/servicepage-top
          jcr:primaryType: hst:containercomponentreference
        hst:componentclassname: uk.nhs.digital.common.components.DocumentChildComponent
        hst:template: service-article
        jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/apppage
      jcr:primaryType: hst:component
