---

group: stable
dist: trusty
language: java

# tmp fix for travis bug
sudo: required

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - travis-test

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.m2"

install:
  - make check.commit-msg
  - make check.yaml

script:
  - make test.travis

notifications:
  slack:
    rooms:
      secure: HjbcDz/CMjB8GIOCE+vBRNNXpGUWixJ7bxj5morpBJy/zOlQsDPub5rewX+imJ/ZeBt9sDwg5M1bavMTOScDZ+I86jdCJoRdLicvXANqWWE92mebY5vLmA7+WXpGCP/YciAhDtpybvLqfbLZqQw3e3g2wQuw/Y3AgD6gDybf22XAR7T5j2Pfu5nBM4+M+E2gxFCAEx1FK387acXz83SemlUiDFYhJyDppyWgIUV6jvBhTPsjFyRJwIUSupPIsDblM8TpI56uHPHjykG8EMETaeeSpkjLobDnOXygzmvI10SxfWaZ9UvBSZSCMumcPo3d1rvozQaf4DtgI/v2N3EIIbcWpcXGKzvtq0PkQqmEznqRO2x6xOvRM4jW5NingUGPsKqOOAJmy7CPG2wmBfs3bP4LfCEEjl6f7/6tILNZmjwP/xkoEhocgMoeHpruODi8CoUgLepdi0V4rQwTEqd2JBBNfx+BgixcxluMCBf9oHw1dON9YEUo3LrS36JQPz8Jm13W/KxX8gq+lj/50Y8deAticeRa9bzB+1nCE5Yv6cWhAU2aaO9bYJ7SjwG1T3Gf+XfKVnr2KqqBJz9JUGWRMgCzSaWdLnNMCi93lLs2Ej9lEKTWSmiPCVKz+4j70v/cWtb9rJbIh/NgHjCUd3bwYUolZlluhvyQy6pb/V6w/Qo=
    on_success: always
    on_failure: always
