name: Slack Deployment Command for ODv2

on:
  repository_dispatch:
    types:
      - slack-deploy-command-odv2

jobs:

  integrity:
    name: Slack Integrity Check
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:

      #
      # Validate that the origin is from Slack
      # See: https://api.slack.com/authentication/verifying-requests-from-slack
      #
      - name: Validate Origin
        uses: actions/github-script@v5
        env:
          AGENT: ${{ github.event.client_payload.integrity.agent }}
          BODY: ${{ github.event.client_payload.integrity.body }}
          TIMESTAMP: ${{ github.event.client_payload.integrity.timestamp }}
          SIGNATURE: ${{ github.event.client_payload.integrity.signature }}
          SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
        with:
          script: |
            if(!`${process.env.AGENT}`.startsWith("Slackbot")){
                core.setFailed("User agent mismatch.")
            } else {
                const base = `v0:${process.env.TIMESTAMP}:${process.env.BODY}`
                const hash = require('crypto').createHmac('sha256', `${process.env.SIGNING_SECRET}`).update(base).digest("hex")
                if(`${process.env.SIGNATURE}` !== `v0=${hash}`) {
                  core.setFailed("The origin integrity check failed.")
                }
            }

      #
      # Provide a URL to the active GitHub Actions Workflow run
      #
      - name: Slack message (Track progress message)
        if: ${{ success() }}
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "${{ env.CHANNEL_ID }}", "text": "Pipeline progress...", "attachments": [{ "text" : "The pipeline logs are here ${{ env.GITHUB_WORKFLOW_URL }}",  "color": "#005EB8" }] }'
        env:
          SLACK_WEBHOOK: ${{  secrets.SLACK_WEBHOOK }}
          GITHUB_WORKFLOW_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          CHANNEL_ID: ${{ github.event.client_payload.data.channel_id }}


  build:
    name: Build Commit
    needs: integrity
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
      BRANCH: ${{ github.event.client_payload.data.text }}
      CHANNEL_ID: ${{ github.event.client_payload.data.channel_id }}
      SLACK_WEBHOOK: ${{  secrets.SLACK_WEBHOOK }}
      USER_ID: ${{  github.event.client_payload.data.user_id }}

    steps:

      #
      # Checkout the branch
      #
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 0 # Need all the tags for versioning

      - name: Slack message (failed to checkout the branch)
        if: ${{ failure() }}
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "${{ env.CHANNEL_ID }}", "text": "Pipeline progress...", "attachments": [{ "text" : "Cannot find the branch named ${{ env.BRANCH }}",  "color": "#DA291C" }] }'


      #
      # Build the branch
      #
      - name: Slack message (building the branch)
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "${{ env.CHANNEL_ID }}", "text": "Pipeline progress...", "attachments": [{ "text" : "Building the branch (${{ env.BRANCH }})", "color": "#78BE20" }] }'

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Get cache key helper values
        uses: actions/github-script@v5
        id: cache-key-helper
        with:
          result-encoding: string
          script: |
            return JSON.stringify({
              "year" : new Date().getFullYear(),
              "rotation" : new Date().getTimezoneOffset()
            })

      - name: Setup cache (Maven packages)
        uses: actions/cache@v2
        env:
          YEAR: ${{ fromJSON(steps.cache-key-helper.outputs.result).year }}
          ROTATION: ${{ fromJSON(steps.cache-key-helper.outputs.result).rotation }}
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-nhs-digital-${{ env.YEAR }}-${{ env.ROTATION }}
          restore-keys: |
            ${{ runner.os }}-maven-nhs-digital-${{ env.YEAR }}-
            ${{ runner.os }}-maven-nhs-digital-
            ${{ runner.os }}-maven-nhs-

      - name: Setup cache (Node.js packages)
        uses: actions/cache@v2
        env:
          YEAR: ${{ fromJSON(steps.cache-key-helper.outputs.result).year }}
          ROTATION: ${{ fromJSON(steps.cache-key-helper.outputs.result).rotation }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-nhs-digital-${{ env.YEAR }}-${{ env.ROTATION }}
          restore-keys: |
            ${{ runner.os }}-node-nhs-digital-${{ env.YEAR }}-
            ${{ runner.os }}-node-nhs-digital-
            ${{ runner.os }}-node-nhs-

      - name: Build and Package Branch
        run: make clean build-odv2
        env:
          HIPPO_MAVEN_PASSWORD: ${{ secrets.HIPPO_MAVEN_PASSWORD }}
          HIPPO_MAVEN_USERNAME: ${{ secrets.HIPPO_MAVEN_USERNAME }}

      - name: Slack message (failed to build the branch)
        if: ${{ failure() }}
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "${{ env.CHANNEL_ID }}", "text": "Pipeline progress...", "attachments": [{ "text" : "Failed to build the branch named ${{ env.BRANCH }}",  "color": "#DA291C" }] }'


      #
      # upload build for next job
      #
      - name: Store Artifact for Later in the Pipeline
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: target/*.tar.gz
          if-no-files-found: error

      - name: Slack message (failed to store artifact for later in the pipeline)
        if: ${{ failure() }}
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "${{ env.CHANNEL_ID }}", "text": "Pipeline progress...", "attachments": [{ "text" : "The pipeline failed to locate the built artifact",  "color": "#DA291C" }] }'

      #
      # Todo: success slack message that gives a link to the GitHub action for downloading the build for debugging.
      #

  upload:
    name: Upload Build to BR Cloud ODv2
    needs:
      - build
    runs-on: ubuntu-latest
    env:
      PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
      BRANCH: ${{ github.event.client_payload.data.text }}
      CHANNEL_ID: ${{ github.event.client_payload.data.channel_id }}
      SLACK_WEBHOOK: ${{  secrets.SLACK_WEBHOOK }}
      USER_ID: ${{  github.event.client_payload.data.user_id }}

    steps:

      #
      # Upload the build
      #
      - name: Slack message (uploading the build)
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "${{ env.CHANNEL_ID }}", "text": "Pipeline progress...", "attachments": [{ "text" : "Preparing to uploading the build to BR ODv2", "color": "#78BE20" }] }'


      # Set up steps.

      #
      # Identify target server
      #
      - name: Identify target
        uses: actions/github-script@v5
        id: find-target
        with:
          result-encoding: json
          script: |
            const environments = {
              C026PH4GQSH: {
                "name": "development",
                "id": "c033120b-291a-463c-8ba7-363fb50ea072",
              }
            }
            if(environments[`${process.env.CHANNEL_ID}`] === undefined) {
              core.setFailed("No target environment has been identifed.")
            } else {
              return environments[`${process.env.CHANNEL_ID}`]
            }

      - name: Slack message (failed to identify the target)
        if: ${{ failure() }}
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "${{ env.CHANNEL_ID }}", "text": "Pipeline progress...", "attachments": [{ "text" : "Cannot find the target server. Are you running the command from the correct channel?",  "color": "#DA291C" }] }'

      - name: Print Identify target for debugging
        run: |
          echo ${{fromJson(steps.find-target.outputs.result).name}}
          echo ${{fromJson(steps.find-target.outputs.result).id}}

      # Get API access token and verify it.
      - name: Obtaino JWT Token
        id: jwt_token
        run: |
          response=$(curl -i \
          -H "Accept: application/json; charset=utf-8" \
          -X POST https://api.${{ secrets.HOST }}/v3/authn/access_token \
          -d '{ "username": "${{ env.USERNAME }}", "password": "${{ env.PASSWORD }}" }')
          token=$(echo $response | awk 'match($0, /access_token":"[^"]+"/) {print substr($0, RSTART+15)}' | cut -d '"' -f 1 )
          refresh=$(echo $response | awk 'match($0, /refresh_token":"[^"]+"/) {print substr($0, RSTART+16)}' | cut -d '"' -f 1 )
          echo "::set-output name=token::$token"
          echo "::set-output name=refresh::$refresh"
        env:
          USERNAME: ${{ secrets.MISSION_CONTROL_API_USERNAME }}
          PASSWORD: ${{ secrets.MISSION_CONTROL_API_PASSWORD }}
      - name: Verify JWT Token
        id: jwt_token_verify
        run: |
          code=$(curl -L \
          -H "Accept: application/json; charset=utf-8" \
          -H "Authorization: Bearer ${{ steps.jwt_token.outputs.token }}" \
          -X GET https://api.${{ secrets.HOST }}/v3/authn/verify_token \
          -o /dev/null -w '%{http_code}\n' -s)
          echo "::set-output name=code::$code"
      - name: Check Response Code from Verify JWT Token
        if: ${{ steps.jwt_token_verify.outputs.code != 200 }}
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed('The JWT token failed verification!')
        env:
          # 'CODE' is for debugging fails
          CODE: ${{ steps.jwt_token_verify.outputs.code }}

      - name: Slack message (failed to identify JWT token)
        if: ${{ failure() }}
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "${{ env.CHANNEL_ID }}", "text": "Pipeline progress...", "attachments": [{ "text" : "Failed to get or verify access to BR ODv2",  "color": "#DA291C" }] }'



      # Main steps
      - name: Download version artifact
        uses: actions/download-artifact@v2
        id: down

      - name: Upload Build to BR Cloud
        id: distribution
        run: |
          filelist=($(ls build/))
          file="dist_file=@build/${filelist[0]}"
          response=$(curl -i \
          -H "Authorization: Bearer ${{ steps.jwt_token.outputs.token }}" \
          -X POST https://api.${{ secrets.HOST }}/v3/distributions \
          -F $file)
          id=$(echo $response | awk 'match($0, /id":"[^"]+"/) {print substr($0, RSTART+5)}' | cut -d '"' -f 1 )
          echo "::set-output name=id::$id"
        working-directory: ${{steps.download.outputs.download-path}}

      - name: Check Response has ID from Upload Build to BR Cloud
        if: ${{ steps.distribution.outputs.id.length == 36 }}
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed('Upload Build to BR Cloud failed!')
        env:
          # For debugging
          ID: ${{ steps.distribution.outputs.id }}
          ID-LENGTH: ${{ steps.distribution.outputs.id.length }}


      - name: Slack message (failed to upload )
        if: ${{ failure() }}
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "${{ env.CHANNEL_ID }}", "text": "Pipeline progress...", "attachments": [{ "text" : "Failed to upload the build",  "color": "#DA291C" }] }'


      #
      # Prepare App Config Deployment Details
      #
      - name: Get Configuration Files Details
        id: files
        run: |
          response=$(curl \
          -H "Authorization: Bearer ${{ steps.jwt_token.outputs.token }}" \
          -X GET https://api.${{ secrets.HOST }}/v3/appconfigfiles)
          echo "::set-output name=details::${response}"

      - name: Get Lastest System Properties for Envrinment
        id: system-properties
        run: |
          id=$(echo '${{steps.files.outputs.details}}' | sed -e 's/+00:00/Z/g' | jq ' . | map( select( .name | startswith( "${{ env.TARGET }}-system-" ) ) ) | sort_by( .createdAt | fromdate ) | reverse | .[0].id')
          echo "::set-output name=id::${id}"
        env:
          TARGET: ${{ fromJson(steps.find-target.outputs.result).name }}

      - name: Get Lastest AWS Keys for Envrinment
        id: aws-keys
        run: |
          id=$(echo '${{steps.files.outputs.details}}' | sed -e 's/+00:00/Z/g' | jq ' . | map( select( .name | startswith( "${{ env.TARGET }}-aws-credentials-" ) ) ) | sort_by( .createdAt | fromdate ) | reverse | .[0].id')
          echo "::set-output name=id::${id}"
        env:
          TARGET: ${{ fromJson(steps.find-target.outputs.result).name }}

      - name: Get Lastest IP Configuration File ID
        id: latest-ip-whitelist
        run: |
          id=$(echo '${{steps.files.outputs.details}}' | sed -e 's/+00:00/Z/g' | jq ' . | map( select( .name | startswith( "hippo-ipfilter-" ) ) ) | sort_by( .createdAt | fromdate ) | reverse | .[0].id')
          echo "::set-output name=id::${id}"


      #
      # Request deployment from ODv2
      #
      - name: Slack message (requesting deployment)
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "${{ env.CHANNEL_ID }}", "text": "Pipeline progress...", "attachments": [{ "text" : "Requesting a deployment on BR ODv2 going to ${{steps.find-target.outputs.result.name}}", "color": "#78BE20" }] }'

      - name: Request Deployment from BR Cloud
        id: deployment
        run: |
          curl -i \
          -H "Accept: application/json; charset=utf-8" \
          -H "Authorization: Bearer ${{ steps.jwt_token.outputs.token }}" \
          -X PUT https://api.${{ secrets.HOST }}/v3/environments/${{ env.ENVIRONMENT }}/deploy \
          -d '{ "distributionId": "${{ env.DISTRIBUTION }}", "strategy" : "rollingupdate", "appConfigFileRoles": [ { "appConfigFileId": ${{ steps.aws-keys.outputs.id }}, "role": "file", "newFilename": "aws-credentials.properties" }, { "appConfigFileId": ${{ steps.system-properties.outputs.id }}, "role": "systemproperty" }, { "appConfigFileId": ${{ steps.latest-ip-whitelist.outputs.id }}, "role": "file", "newFilename": "hippo-ipfilter.properties" } ] }'
        env:
          DISTRIBUTION: ${{ steps.distribution.outputs.id }}
          ENVIRONMENT: ${{ fromJson(steps.find-target.outputs.result).id }}

      - name: Check Response Code from Request Deployment from BR Cloud
        if: ${{ steps.deployment.outputs.code >= 200 && steps.deployment.outputs.code < 300 }}
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed('Request Deployment from BR Cloud failed!')

      - name: Slack message (failed to deploy)
        if: ${{ failure() }}
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "${{ env.CHANNEL_ID }}", "text": "Pipeline progress...", "attachments": [{ "text" : "BR ODv2 failed to request a deployment",  "color": "#DA291C" }] }'


      # Clean-up steps below.

      # Delete JWT refresh token
      - name: Request Deletion of JWT Refresh Access tokens
        if: always()
        id: jwt_token_invalidate
        run: |
          code=$(curl -L \
          -H "Accept: application/json; charset=utf-8" \
          -X DELETE https://api.${{ secrets.HOST }}/v3/authn/refresh_token \
          -d '{ "grant_type": "refresh_token", "refresh_token": "${{ env.REFRESH }}" }' \
          -o /dev/null -w '%{http_code}\n' -s)
          echo "::set-output name=code::$code"
        env:
          REFRESH:  ${{ steps.jwt_token.outputs.refresh }}
      - name: Check Response Code from Deletion of JWT Refresh Access tokens
        if: ${{ steps.jwt_token_invalidate.outputs.code != 200 }}
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed('The JWT Deletion of JWT Refresh Access tokens failed!')
        env:
          # 'CODE' is for debugging fails
          CODE: ${{ steps.jwt_token_invalidate.outputs.code }}


      #
      # End with a success message
      #
      - name: Slack message (end message)
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "${{ env.CHANNEL_ID }}", "text": "Pipeline progress...", "attachments": [{ "text" : "BR ODv2 is deploying. <@${{ env.USER_ID }}> You can track progress here https://missioncontrol.${{ secrets.HOST }}/#/environment/${{ fromJson(steps.find-target.outputs.result).id }}/details", "color": "#78BE20" }] }'


      - name: Slack message (Always end message)
        if: ${{ always() }}
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "${{ env.CHANNEL_ID }}", "text": "Pipeline Finished", "attachments": [{ "text" : "End of communication. You have a great day now.",  "color": "#005EB8" }] }'